apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: sentiment-drift
  labels:
    app: api-gateway
    component: config
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    
    http {
        upstream sentiment_analysis {
            server sentiment-analysis-service:8001;
        }
        
        upstream drift_detection {
            server drift-detection-service:8002;
        }
        
        upstream session_management {
            server session-management-service:8003;
        }
        
        upstream response_adaptation {
            server response-adaptation-service:8004;
        }
        
        upstream analytics {
            server analytics-service:8005;
        }
        
        # Rate limiting
        limit_req_zone $binary_remote_addr zone=api:10m rate=10r/s;
        limit_req_zone $binary_remote_addr zone=analysis:10m rate=100r/m;
        
        server {
            listen 8000;
            server_name _;
            
            # Security headers
            add_header X-Frame-Options "SAMEORIGIN" always;
            add_header X-XSS-Protection "1; mode=block" always;
            add_header X-Content-Type-Options "nosniff" always;
            add_header Referrer-Policy "no-referrer-when-downgrade" always;
            add_header Content-Security-Policy "default-src 'self'" always;
            
            # Health check
            location /health {
                return 200 "OK";
                add_header Content-Type text/plain;
            }
            
            # API routes with rate limiting
            location /api/v1/sentiment/ {
                limit_req zone=analysis burst=20 nodelay;
                proxy_pass http://sentiment_analysis;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
            
            location /api/v1/drift/ {
                limit_req zone=api burst=10 nodelay;
                proxy_pass http://drift_detection;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
            
            location /api/v1/sessions/ {
                limit_req zone=api burst=10 nodelay;
                proxy_pass http://session_management;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
            
            location /api/v1/response/ {
                limit_req zone=api burst=10 nodelay;
                proxy_pass http://response_adaptation;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
            
            location /api/v1/analytics/ {
                limit_req zone=api burst=5 nodelay;
                proxy_pass http://analytics;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
            
            # Default route
            location / {
                return 404 "Not Found";
            }
        }
    }
