apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: sentiment-drift
  labels:
    app: postgresql
    component: config
data:
  postgresql.conf: |
    # PostgreSQL configuration for sentiment drift tool
    
    # Connection settings
    listen_addresses = '*'
    port = 5432
    max_connections = 100
    
    # Memory settings
    shared_buffers = 256MB
    effective_cache_size = 1GB
    maintenance_work_mem = 64MB
    checkpoint_completion_target = 0.9
    wal_buffers = 16MB
    default_statistics_target = 100
    random_page_cost = 1.1
    effective_io_concurrency = 200
    
    # Write ahead log
    wal_level = replica
    max_wal_senders = 3
    max_replication_slots = 3
    
    # Query tuning
    default_statistics_target = 100
    random_page_cost = 1.1
    effective_io_concurrency = 200
    
    # Logging
    log_destination = 'stderr'
    logging_collector = on
    log_directory = 'pg_log'
    log_filename = 'postgresql-%Y-%m-%d.log'
    log_statement = 'all'
    log_min_duration_statement = 1000
    
    # Time zones
    timezone = 'UTC'
    
  pg_hba.conf: |
    # PostgreSQL Client Authentication Configuration File
    
    # TYPE  DATABASE        USER            ADDRESS                 METHOD
    local   all             all                                     trust
    host    all             all             127.0.0.1/32            md5
    host    all             all             ::1/128                 md5
    host    all             all             0.0.0.0/0               md5
