apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-management-deployment
  namespace: sentiment-drift
  labels:
    app: session-management
    component: microservice
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: session-management
  template:
    metadata:
      labels:
        app: session-management
        component: microservice
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8003"
    spec:
      initContainers:
      - name: migrate-db
        image: sentiment-drift/session-management:latest
        command: ["alembic", "upgrade", "head"]
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: db-secrets
      containers:
      - name: session-management
        image: sentiment-drift/session-management:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8003
          name: http
        env:
        - name: SERVICE_NAME
          value: "session-management"
        - name: PORT
          value: "8003"
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: db-secrets
        - secretRef:
            name: api-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 5
          periodSeconds: 5
      restartPolicy: Always
