apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  namespace: sentiment-drift
  labels:
    app: postgresql
    component: database
spec:
  selector:
    app: postgresql
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
    protocol: TCP
  type: ClusterIP
---
# Headless service for StatefulSet
apiVersion: v1
kind: Service
metadata:
  name: postgresql-headless
  namespace: sentiment-drift
  labels:
    app: postgresql
    component: database
spec:
  selector:
    app: postgresql
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
    protocol: TCP
  type: ClusterIP
  clusterIP: None
